SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS web_store;

CREATE DATABASE web_store;

USE web_store;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(70) NOT NULL UNIQUE,
    password CHAR(64) NOT NULL,
    profile_picture VARCHAR(255),
    role_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    producer_id INT NOT NULL,
    is_available TINYINT NOT NULL
);

CREATE TABLE IF NOT EXISTS producers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS shopping_cart (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL
);

ALTER TABLE users
ADD FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE products
ADD FOREIGN KEY (producer_id) REFERENCES producers (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE shopping_cart
ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE shopping_cart
ADD FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO roles (name) VALUES ('administrator'), ('guest');

SET FOREIGN_KEY_CHECKS = 1;